### PR TITLE
Fix issue 289 -  edit default error

### LINKED ISSUE #289: Feature "Edit Defaults" does not work
### Summary
Users get error when using `Edit Defaults` feature in the batch editor

### Steps to Reproduce
1. Open Batch Editor (PsPM -> Batch)
2. Select `Edit Defaults` under `PsPM` in the menu bar.

### Expected Results
Users can edit these modules.

Brace indexing is not supported for variables of this type.
Error in cfg_ui_util (line 120)
            cfg_util('listmod', cmid{:}, [],...
Error in cfg_ui>local_showmod (line 329)
    [id, namestr, datastr, contents] = cfg_ui_util('showmod', cmid, dflag);
Error in cfg_ui>local_editdefs (line 248)
local_showmod(gcbo);
Error while evaluating Menu Callback.

### Technical Info
* MATLAB version: 5.1.0

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #289.

Changes proposed in this pull request:
- Fix grammar mistakes that lead to error when clicking "edit defaults".

### CODE REVIEW

File: src/pspm_cfg/pspm_cfg_import.m [hunk 1]
```diff
@@ -88,7 +88,7 @@
 scr_input.tag   = 'input';
```
Comment (teddychao) [inline src/pspm_cfg/pspm_cfg_import.m:88]: This file is not modified. Some blanks were left due to reverting some old commits.

File: src/pspm_cfg/pspm_cfg_run_import.m [hunk 2]
```diff
@@ -26,7 +26,7 @@
     % Importtype
```
Comment (teddychao) [inline src/pspm_cfg/pspm_cfg_run_import.m:26]: This file is not modified. Some blanks were left due to reverting some old commits.

**Review by dominikbach — APPROVED** [review]
