### PR TITLE
Fix issue 302 - test mode for PsPM

### LINKED ISSUE #302: Test mode for PsPM
### Feature Description

Option to allow silent or simplified running report in Terminal

Currently PsPM will try to export the essential processing report in MATLAB terminal. Sometimes, users may be just interested in whether the processing completes successfully instead of knowing the details, especially for those who use GUI. Therefore, is it possible to add an option in PsPM, which allows to silent or simplify the terminal report?

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #302.

Changes proposed in this pull request:
- Update to provide an option of develop mode
- Add a new function `pspm_overwrite` to handle overwriting operations.

Please kindly keep this pull request open after approving it because I need to sort out some formatting issues and documents that I have not finished. Thanks.

### CODE REVIEW

File: src/backroom/pspm_scr2ledalab.m [hunk 1]
```diff
@@ -101,23 +101,15 @@
...
-    end             
-    close gcf;
-else
-    overwrite = 'Yes';
-end;
-if strcmp(overwrite, 'No')
-    warning('Data discarded ...');
-    return;
+
+if pspm_overwrite(outfile, options)
```
Comment (jbrochar) [inline src/backroom/pspm_scr2ledalab.m:105]: [minor comment]
For consistency, shouldn't the syntax be:
```
write_ok = pspm_overwrite(options.output_file, options);
if write_ok
```
as in src/backroom/pspm_find_data_epochs.m line 103?

File: src/backroom/pspm_scr2ledalab.m [hunk 2]
```diff
@@ -101,23 +101,15 @@
...
+	save(outfile, 'data', 'fileinfo');
 else
-    save(outfile, 'data', 'fileinfo');
-end;
+	warning('Data discarded ...');
```
Comment (jbrochar) [inline src/backroom/pspm_scr2ledalab.m:108]: [minor comment]
Would a naive user reading this warning be able to understand where it comes from and why?
Could it be extended with more information, while still being easy to read?

File: src/pspm_overwrite.m [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+% pspm_overwrite generalises the overwriting operation
+% pspm_overwrite considers the following situations
+% - whether options.overwrite is defined
+% - whether PsPM is in develop mode
+% - whether the file exist
+% - whether GUI can be used
+% Only the following situation will stop PsPM to overwrite files
+% 1. if overwrite is defined as not to overwrite
+% 2. if overwrite is not defined, and users use the GUI to stop overwriting
+
```
Comment (jbrochar) [inline src/pspm_overwrite.m:13]: Wouldn't this blank line (without a `%` at the beginning) prevent the documentation to be correctly generated?
With and without a `%` it gives me a full or a truncated help section.
image
image

File: src/pspm_overwrite.m [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+% ow        option of overwrite if this option is presented
+%           can be a value or a struct
+%           if a value, can be 0 (not to overwrite) or 1 (to overwrite)
+%           if a struct, check if the field "overwrite" exist
+
+% OUTPUTS
+% ow_final  option of overwriting determined by pspm_overwrite
+
+pth = fileparts(which('pspm'));
+settings_struct = load([pth, '/pspm_settings.mat'], "settings");
```
Comment (jbrochar) [inline src/pspm_overwrite.m:26]: [minor comment]
Isn't it time-consuming to load the settings like that each time, instead of using a global variable?
It is a genuine question, it might not worth the effort to change this way of doing.

File: src/pspm_overwrite.m [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+    return;
+  case 1 % ow is not defined
+    fn = varargin{1};
+    if iscell(fn)
+      fn = fn{1};
+    end
+    switch settings.developmode
+      case 1
+        ow_final = 1; % In develop mode, always overwrite
+      otherwise
```
Comment (jbrochar) [inline src/pspm_overwrite.m:44]: It is a bit confusing to use a switch for a single case.
Are you planning to add multiple `settings.developmode` in the future?
If so, please discard this comment.

File: src/backroom/pspm_scr2ledalab.m (hunk 2 above)
Comment (dominikbach) [reply src/backroom/pspm_scr2ledalab.m:108]: Just to clarify: "Backroom" includes functions that cannot be accessed from the GUI - this is for development and legacy purposes.

**Review by dominikbach — COMMENTED** [review]
Just two generic comments:
- pspm_overwrite seems a very good idea
- in general I'd suggest not touching backroom functions (even if incompatible with the main code) as they are kept for legacy and development purposes only

**Review by jbrochar — APPROVED** [review]
There are still a few minor comments of mine here and there, but I'll let Teddy judge if they should lead to code change or not, none of them are critical.

File: src/backroom/pspm_scr2ledalab.m (hunk 2 above)
Comment (teddychao) [reply src/backroom/pspm_scr2ledalab.m:108]: > [minor comment]
> Would a naive user reading this warning be able to understand where it comes from and why?
> Could it be extended with more information, while still being easy to read?

Yes.. Some warnings caused by overwriting are proposed in `pspm_overwrite` thus they are not repeated here. I am not the author of this script so I have not done any updates in this function but just applied the new APIs.

File: src/pspm_overwrite.m (hunk 3 above)
Comment (teddychao) [reply src/pspm_overwrite.m:13]: Yes... I have deleted that blank line break.

File: src/backroom/pspm_find_data_epochs.m [hunk 6]
```diff
@@ -99,24 +99,8 @@
...
-            ov = 'Yes'; % default to overwrite on Jenkins
-        end
-        write_ok = strcmp(ov,'Yes');
-    end;
-else
-    write_ok = true;
-end;
 
+write_ok = pspm_overwrite(options.output_file, options);
 if write_ok
```
[the remark this answers is not in the document]
Comment (teddychao) [reply src/backroom/pspm_find_data_epochs.m:104]: I agree this should be consistent throughout these functions. I tried to make it clear as the output of pspm_overwrite can be found in its help text. Producing less variables may make the software run faster.

File: src/pspm_overwrite.m (hunk 5 above)
Comment (teddychao) [reply src/pspm_overwrite.m:40]: > It is a bit confusing to use a switch for a single case.
> Are you planning to add multiple `settings.developmode` in the future?
> If so, please discard this comment.

I wrote it like that because `settings.developmode` may be defined as something else and I want to avoid such bugs... However I agree it is a little confusing. I have changed it to logical values now.

**Comment by teddychao** [comment]
> Just two generic comments:
> 
> * pspm_overwrite seems a very good idea
> * in general I'd suggest not touching backroom functions (even if incompatible with the main code) as they are kept for legacy and development purposes only

No problem, thanks for reminding. I have reverted the backroom functions.
