### PR TITLE
Fix markerinfo handling

### LINKED ISSUE #670: bug in `pspm_get_markerinfo`
### Summary

```
Brace indexing is not supported for variables of this type.
In file "/Users/dominik/Documents/PublicData/PsPM/src/pspm_get_markerinfo.m" (???), function "pspm_get_markerinfo" at line 70.
```

### LINKED ISSUE #672: problem running GLM with conditions created from markerinfo
potentially linked to #670 via a faulty markerinfo structure?
```
------------------------------------------------------------------------
21-Mar-2024 09:14:49 - Running job #1
------------------------------------------------------------------------
21-Mar-2024 09:14:49 - Running 'GLM for SCR'
Warning: markerinfo must be a field in the struct 
> In pspm_get_timing (line 341)
In pspm_check_model (line 263)
In pspm_glm (line 164)
In pspm_cfg_run_glm_scr (line 26)
In cfg_run_cm (line 29)
In cfg_util>local_runcj (line 1706)
In cfg_util (line 966)
In cfg_ui>MenuFileRun_Callback (line 705)
In gui_mainfcn (line 95)
In cfg_ui (line 53) 
21-Mar-2024 09:14:50 - Done    'GLM for SCR'
21-Mar-2024 09:14:50 - Done
```

Matlabbatch script:
```
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.modelfile = 'test';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.outdir = {'/Users/dominik/Documents/PublicData/Sandbox'};
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.chan.chan_def = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.timeunits.seconds = 'seconds';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.session.datafile = {'/Users/dominik/Documents/PublicData/Sandbox/pspm_PP12.mat'};
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.session.missing.no_epochs = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.session.data_design.marker_cond.marker_values.marker_values_val = 1;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.session.data_design.marker_cond.cond_names = {'test'};
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.session.nuisancefile = {''};
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.latency.fixed = 'fixed';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.bf.scrf1 = 1;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.norm = false;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.filter.def = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.exclude_missing.excl_no = 'No';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.glm_scr.overwrite = false;
```

### PR DESCRIPTION
**Pull request by dominikbach**
Fixes #670 and fixes #672 .

Changes proposed in this pull request:
1. #670 was caused by a faulty markerinfo structure in a file that had been preprocessed multiple times. It is unclear what caused this faulty structure; it did not appear when the file was re-imported. Added a check for the markerinfo structure in `pspm_check_data` to catch such cases.
2. A potential root cause for (1) is the function `pspm_combine_markerchannels` which creates a char rather than cell array for `markerinfo.name`. This was fixed.
4. #672 was caused in `pspm_get_timing`, called by `pspm_check_model`. This check will fail because at this point, the data (and therefore, the markerinfo structure) has not yet been loaded. `pspm_check_model` is now adapted.
5. A bug in `pspm_cfg_run_glm` was removed.
6. Option to work on multiple data files for `pspm_combine_markerchannels` was removed, in line with #689.

### CODE REVIEW

File: src/pspm_combine_markerchannels.m [hunk 1]
```diff
@@ -8,17 +8,16 @@
 % ● Format
 %   [sts, outchannel] = pspm_combine_markerchannels(datafile, options)
 % ● Arguments
-%    datafile:          data file name(s) (char, or cell array for 
-%                       multiple files)
+%    datafile:          data file name(s): char
```
Comment (teddychao) [inline src/pspm_combine_markerchannels.m:11]: Just to confirm my understanding. Loading multiple files is no longer supported after this update. Only one file is allowed to be imported.

**Review by teddychao — APPROVED** [review]

**Comment by teddychao** [comment]
Looks good to me. I do not have further concerns. Thank you for the bug fixes.
