### PR TITLE
Fix issue 552 -- spike-smrx

### LINKED ISSUE #552: Import spike smrx files
### Feature Description

PsPM reads the older spike smr-format but not the newer smrx-format. 

Resources:
https://ced.co.uk/upgrades/spike2matson
https://github.com/brainstorm-tools/brainstorm3/commit/b18a1bf642bf01b0c6745a30a8fc788bebb89375

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #552 .

### Summary
This pull request provides the feature of importing `.smrx` files into PsPM.
According to the requirement of CED library, the support of `.smrx` will be available on only 64bit Windows.

### Method
1. The import method of `.smrx` is following `.smr`.
2. The data importing function is from CED's internal library.

#### General
1. `pspm_get_spike` was originally used for importing `smr` data. To avoid confusion, `pspm_get_spike` has been renamed into `pspm_get_smr`, and `smrx` is now using `pspm_get_smrx`.
3. The `CEDS64ML` package is now added to PsPM as an external package. Currently, `smrx` will need the functions in `CEDS64ML` to import `smrx` data.
#### `pspm_init`
1. The specifications for `smrx` has been added to `pspm_init`, following the specification of `smr`.

### Current achievements
* Now SMRX files can be read with the new function `pspm_get_smrx`, to read `waveform` or `events`. However, there have been no `marker` channels in the test data.
* The GUI has now supported SMRX.
image

### Status (19-Feb-2024)
| `.data` | `kind` | Solution | Reason |
| :-- | :-- | :-- | :-- |
| `wave` | 0 | Return | The channel is empty, so import nothing. Warning and return. |
| `wave` | 1 | Import | Import as `waveform` by using `CED64ReadWaveF` | 
| `wave` | 2 | Return | Not mentioned in `smr`, currently categorised into `otherwise`. |
| `wave` | 3 | Import | Import as `timestamps` by using `CED64ReadWaveF` with minor adjustments | 
| `wave` | 4 | Import | Import as `up and down time stamps` by using `CED64ReadWaveF` with minor adjustments | 
| `wave` | otherwise | Return | Warning and return. |
| `events` | 0 | Return | Warning and return. |
| `events` | 1 | Import | Import as `events` by using `CEDS64ReadEvents`. |
| `events` | 2 | Import | Not mentioned in `smr`, currently categorised into `otherwise`. |
| `events` | 3 | Import | Not mentioned in `smr`, currently do nothing and show a warning `feature unavailable`. |
| `events` | 4 | Import | Import as `marker` channel by using `CEDS64ReadMarkers` with minor adjustments. | 
| `events` | otherwise | Import | Import as `marker` with some fixed parameters. |
| otherwise | / | Return | currently do nothing. Shall there be a fallback? |

### Field checking
| `.data` | kind | data | length | sr | marker |
| :-- | :-- | :-- | :-- | :-- | :-- |
| `wave` | 1 | ←`ReadWaveF` | ←`ReadWaveF` | `.realRate` | ? |
| `wave` | 3 | ←`ReadWaveF` | ←`ReadWaveF` | `.realRate` | ? |
| `wave` | 4 | ←`ReadWaveF` | ←`ReadWaveF` | `.realRate` | ? |
| `events` | 1 | ←`ReadEvents` | ←`ReadWaveF` | `.realRate` or `.idealRate`  | `continuous` |
| `events` | 4 | ←`ReadMarkers` | ←`ReadMarkers` | `.realRate` or `.idealRate` | `timestamp` |
| `events` | otherwise | ←`ReadMarkers` | ←`ReadMarkers` | 0.001 | `timestamp` |

Fields not used: `minfreq`.
Fields inheriting from `fileinfo` (alphabetically): `div`, `gain`, `idealRate`, `number`, `realRate`, `title`, `units`.

### References
CEDS64: https://ced.co.uk/upgrades/spike2matson

### CODE REVIEW

**Comment by dominikbach** [comment]
In the example data file 25.10.2023, the markers are in channel 10, which is of type 4. The current version of the function does not read the data, but it reads the name into the first cell of `MarkerChanName`. The name of this channel is "Ext. Pulses". The function should:
- consecutively read data from all channels that are not empty, including channels of the types specified in line 65 of `pspm_get_smrx`.
- In line with other PsPM import functions, the user should select channels by their index (i.e. the n.-th *existing* channel in the file). For the marker channel in this example, the channel index would be 5.
- please update.

**Comment by teddychao** [comment]
> In the example data file 25.10.2023, the markers are in channel 10, which is of type 4. The current version of the function does not read the data, but it reads the name into the first cell of `MarkerChanName`. The name of this channel is "Ext. Pulses". The function should:
> 
> * consecutively read data from all channels that are not empty, including channels of the types specified in line 65 of `pspm_get_smrx`.
> * In line with other PsPM import functions, the user should select channels by their index (i.e. the n.-th _existing_ channel in the file). For the marker channel in this example, the channel index would be 5.
> * please update.

I have understood the issue. I was not aware marker channels were counted in another array. I can updated it based on the given information now.

File: src/pspm_get_smr.m [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+  end
+  sourceinfo.channel{iImport, 1} = sprintf('Channel %02.0f: %s', channel, chanhead{channel}.title);
+  % 3.1.2 convert to waveform or get sample rate for wave channel types
+  if strcmpi(settings.channeltypes(import{iImport}.typeno).data, 'wave')
+    if chanhead{channel}.kind == 1 % waveform
+      import{iImport}.data = chandata{channel};
+      import{iImport}.sr   = 1./chanhead{channel}.sampleinterval;
+    elseif chanhead{channel}.kind == 3 % timestamps
+      % get minimum frequency for reporting resolution
+      import{iImport}.minfreq = min(1./diff(chandata{channel}))*1000;
```
Comment (teddychao) [inline src/pspm_get_smr.m:78]: For `minfreq`, there are two lines: line 78 and 82. I am unsure if they are repeating lines?
