### PR TITLE
Fix issue 355 - zero index issue in ValidSamplesModel.m

### LINKED ISSUE #355: pupil combined processing error
### Summary
For 1 of my participants Matlab throws an error and quits further preprocessing of combined pupil data. The error originates in indexing a matrix with zero in ...\PsPM\src\ext\pupil-size\code\dataModels\ValidSamplesModel.m line 147. The indices come from a histogram bin count.
### Steps to Reproduce
1. Run pspm_pipline_QC cell 1. Enter subject number 15 visit 2.
2. Run cell 3: (2) Import, trim, and find valid fixation in Eyelink. This will run the pspm_pipline_prepare_edf_CFG_comb function. 
=>The error occurs in ...\PsPM\src\ext\pupil-size\code\dataModels\ValidSamplesModel.m line 147 only for combined eye data. No error for single eye data.

### Expected Results
Run pspm_pipline_QC cell 1. Enter subject number 13 visit 2 as a comparison for which preprocessing works.
### (Optional) Possible Cause and Solutions
When I use the code version that is commented out that uses discretize the preprocessing runs smoothly.

### Technical Info
* PsPM version: 5.1.1
* MATLAB version: 2021b
[pupil_comb_error.zip](https://github.com/bachlab/PsPM/files/8179253/pupil_comb_error.zip)

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #355.

Changes proposed in this pull request:
- Update `ValidSamplesModel.m`
  - Histogram counts could be 0 which will lead to error in the next step of processing. We control this by removing the calculated 0 and also throw a warning if there are too many zeros there.

### CODE REVIEW

**Review by dominikbach — APPROVED** [review]

File: src/ext/pupil-size/code/dataModels/ValidSamplesModel.m [hunk 1]
```diff
@@ -144,6 +144,11 @@ function interpAndSmooth(obj)
             valz          = [diff(valid_t_ms);NaN];
```
Comment (jbrochar) [inline src/ext/pupil-size/code/dataModels/ValidSamplesModel.m:144]: image
careful with the character encoding

Comment (teddychao) [reply src/ext/pupil-size/code/dataModels/ValidSamplesModel.m:144]: Yes, this is the conflict of LF (Unix) and CRLF (Windows)... This should be resolved in the pull request 130, which converted all the functions into LF and UTF-8.
