### PR TITLE
initial commit to fix #571

### LINKED ISSUE #571: pspm_dcm does not use missing data periods shorter than the threshold
### Summary
pspm_dcm drops information on missing data epochs shorter than the threshold.

### Steps to Reproduce
line 249: data is written into a variable `y`: `y{iSn} = data{iSn}{end}.data;`
In line 297, missing epochs are converted to NaN in the data: `y{iSn}(flanks(1):flanks(2)) = NaN;`

After taking care of missing epochs longer than the threshold, missing epochs are identified from the data in line 361-362. However, instead of using the variable `y` previously modified, the data are again read from the original data structure:
```
sbSn_data = data{sbSn(1)}{1}.data(flanks(1):flanks(2));
sbs_miss = isnan(sbSn_data);
```

As a result, non-interpolated artefacts show up in the model inversion.

### PR DESCRIPTION
**Pull request by dominikbach**
Fixes #571  .

Changes proposed in this pull request:
- fix a bug in pspm_dcm that leads dropping sub-threshold missing data periods
- enable combining missing data epochs from file and data (as in a recent use case in CogLearn)

### CODE REVIEW

File: src/pspm_dcm.m [hunk 1]
```diff
@@ -358,7 +362,7 @@
   isbSn = valid_subsessions(vs);
   sbSn = subsessions(isbSn, :);
   flanks = pspm_time2index(sbSn(2:3), data{sbSn(1)}{1}.header.sr);
```
Comment (teddychao) [inline src/pspm_dcm.m:364]: Just a suggestion, should `data{sbSn(1)}{1}.header.sr` be `sr{sbSn(1)}`?

**Comment by teddychao** [comment]
My understanding is this pull request would like to make the code between lines 278 and 298 to be working regardless of the condition of `missing{iSn}`. This makes sense to me. I only have a suggestion of line 360, but it is not a strong opinion.

**Review by teddychao — APPROVED** [review]

File: src/pspm_dcm.m (hunk 1 above)
Comment (dominikbach) [reply src/pspm_dcm.m:364]: This is not something I have changed; so I'd suggest leaving this for a separate pull request.
