### PR TITLE
fix 587

### LINKED ISSUE #587: Problem running single-session DCM
### Summary
DCM does not run from GUI.

### Steps to Reproduce
1. Use non-linear tutorial instructions

### Expected Results
Model runs through

### Actual Results
Model fails (see screenshot)
image

### (Optional) Possible Cause and Solutions
`pspm_check_model` wrongly turns a cell array of char into a cell array of cell arrays in line 209.

### Technical Info
* PsPM version: 6.1.1
* MATLAB version: 2023a

### PR DESCRIPTION
**Pull request by dominikbach**
Fixes #587  .

Changes proposed in this pull request:
- fix `pspm_check_model`
- 
-

### CODE REVIEW

**Review by uzaygokay — APPROVED** [review]

File: src/pspm_check_model.m [hunk 1]
```diff
@@ -201,11 +201,11 @@
 else
   if ~isempty(model.timing)
     if ~iscell(model.timing) || ...
-      strcmpi(modeltype, 'dcm') && ~iscell(model.timing{1})
+      (strcmpi(modeltype, 'dcm') && ~iscell(model.timing{1}) && ~ischar(model.timing{1}))
       % for DCM, model.timing is either a file name or a cell array of
       % events, or a cell array of file names or cell arrays, so we need to
```
Comment (teddychao) [inline src/pspm_check_model.m:206]: I am a little confused about this... It says `model.timing` can be a cell array of filenames, but it cannot be a cell array of char. I think a filename is a char..?

Comment (dominikbach) [reply src/pspm_check_model.m:206]: Hi Teddy, the comment does not actually say that "`model.timing` cannot be a cell array of char". Of course it can. The comment only says that we need to find the case where `model.timing` is a cell array, but NOT a cell array of char or of cell arrays (which are both perfectly permissible)
