### PR TITLE
Fix issue 284

### LINKED ISSUE #284: Test function for pspm_bf_data
### Feature Description
_pspm_bf_data_ is a newly implemented function that provides a generic interface for creating a user-defined response function from a data vector saved in a *.mat file.
A test function is required for maintaining this function.

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #284  .

Changes proposed in this pull request:
- Update the general test function *pspm_bf_test* by adding support of the newly implemented *pspm_bf_data*.

### CODE REVIEW

File: test/pspm_test_temp.m [hunk 1]
```diff
@@ -0,0 +1,122 @@
+function pspm_test_temp(varargin)
```
Comment (teddychao) [inline test/pspm_test_temp.m:1]: This is a function for temporary testing only selected functions. It will be removed when merging it to the develop branch.

**Review by dominikbach — APPROVED** [review]
