### PR TITLE
Fix-272

### LINKED ISSUE #272: Split sessions file loading issue
### Summary

Split sessions should accept data file and missing epoch file as char variables from either GUI or scripts. However, users reported currently the missing epoch file was not accepted sometimes. It is useful to check if the information of data file and missing epoch files are delivered correctly to the function.

### PR DESCRIPTION
**Pull request by dominikbach**
Fixes #272  .

Changes proposed in this pull request:
- allow splitting of empty missing epochs in pspm_split_sessions for compatibility with pspm_scr_pp

### CODE REVIEW

**Review by teddychao — APPROVED** [review]

File: src/pspm_split_sessions.m [hunk 1]
```diff
@@ -166,8 +166,11 @@
         missing = round(missing*missingsr); % convert epochs in sec to datapoints
     end
     indx = zeros(1,round(missingsr * ininfos.duration)); % indx should be a one-dimensional array?
-    indx(missing(:, 1)) = 1;
-    indx(missing(:, 2)+1) = -1;
+    % allow splitting empty missing epochs
```
Comment (teddychao) [inline src/pspm_split_sessions.m:169]: I agree the old code always take effects on the missing epochs, which is not expected. It should be applied to missing epochs when users define missing epoch files.
